<%@ Page Title="Legal Information | Genie Garage Door Openers" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="terms.aspx.cs" Inherits="terms" %>
<%@ MasterType TypeName="MasterPage" %>
<%@ Register src="../controls/company-menu.ascx" tagname="menu" tagprefix="company" %>

<asp:Content ID="Content1" ContentPlaceHolderID="headcontent" Runat="Server">
	<meta id="Meta1" name="robots" runat="server" content="index, follow" />
    <meta id="description" name="description" runat="server" content="The Genie Company - Legal Information" />
    <meta id="keywords" name="keywords" runat="server" content="genie company legal information, terms, privacy policy, garage door openers, garage doors" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Body" Runat="Server">

<h1>Legal Information</h1>

<!-- company menu -->
<company:menu runat="server" ID="company" />

<h2>TERMS AND CONDITIONS OF USE</h2>
<p>GMI Holdings Inc. d/b/a The Genie (R) Company is a subsidiary of Overhead Door Corporation, an Indiana Corporation ("Genie" for purposes of this website). Genie grants you ("User") permission to view www.GenieCompany.com, the ("Site"), provided that you agree to and accept without modification the notices, terms and conditions set forth in this agreement ("Terms").  Your use of this Site constitutes your agreement and acceptance without modification of the notices, terms and conditions set forth herein. In addition, as a condition of your use of this Site, you represent and warrant that you will not use this Site for any purpose that is unlawful, immoral or prohibited by these terms, conditions and notices. If you do not agree and accept without modification the notices, terms and conditions set forth herein, do not use this Site.</p>

<h2>GENERAL DISCLAIMER</h2>
<p>Genie does not warrant or endorse the accuracy or reliability of the information contained on, distributed through or linked to or downloaded or accessed from this Site and does not warrant or endorse the quality of any software or other products, information or other materials displayed, purchased or obtained by a User as a result of any advertisement or any information or offer made in or through this Site. Local regulations vary substantially, and Genie does not warrant that the information available from this Site complies with building codes, ordinances, or regulations for any particular application or in any particular jurisdiction, without Genie's express written agreement.</p>
<p>Genie is constantly improving its information, products and services. Consequently, Genie cannot and does not guarantee the accuracy or completeness of the information, including prices, product images, specifications, availability and services.</p>
<p>Any purchase by User of any products or services manufactured or supported by Genie shall be subject to all of the standard terms and conditions set forth in Genie's purchase and sale terms and conditions applicable to the purchase.</p>

<h2>COPYRIGHT AND TRADEMARKS</h2>
<p>Genie takes seriously legal copyright, trademark and privacy laws. Visitors of this Web site and customers of Genie shall abide by the following notice: The copyrights, trademarks, other intellectual property and all materials provided on this Site are owned, controlled, or licensed by Genie, one of its affiliates or by the original owner and are protected by U.S. and international laws.  None of the text, content, materials, names, logos, trademarks or other marks on this Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means, including, but not limited to, electronic, mechanical, photocopying, recording or otherwise. You also may not, without Genie's permission, "mirror" any materials contained on this Site on any other server.  Any unauthorized use of any materials contained on this Site may violate copyright laws, trademark laws, the laws of privacy and publicity, and communications regulations and statutes. The trademarks, logos, meta tags and service marks displayed on this Site, including the trademark "Genie" and other trademarks used by Genie (collectively, the "Marks"), are the property of Genie. Users are prohibited from using any Mark for any purpose.</p>

<h2>LINKED INTERNET WEB SITES</h2>
<p>Genie has provided Internet links to other Web sites for User's convenience. Most Web sites linked to this Site are owned and operated independently of Genie. As a result, Genie has no control over the products, materials, services or other information contained in or available through these third-party Web sites. The quality and reliability of these third party Web sites may vary as they are updated or altered. Genieâ€™s inclusion of links to an outside Site does not imply any endorsement of the material on the Site or, unless expressly disclosed otherwise, any sponsorship, affiliation or association with its owner, operator or sponsor, nor does Genieâ€™s inclusion of the links imply that Genie is authorized to use any trade name, trademark, logo, legal or official seal or copyrighted symbol that may be reflected in the linked Site. The User acknowledges that access to any other Web sites linked to this Site is at the User's own risk.</p>

<h2>NO WARRANTIES</h2>
<p>EXCEPT FOR AVAILABLE WRITTEN EXPRESS WARRANTIES FOR GENIE'S PRODUCTS DESCRIBED ON THIS SITE, THE MATERIALS, DRAWINGS, SPECIFICATIONS, PRODUCTS AND OTHER RESOURCES AVAILABLE FROM THIS SITE ARE PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW. GENIE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND GENIE DOES NOT WARRANT THAT THE DISSEMINATION OF THE INFORMATION WILL BE ERROR FREE OR UNINTERRRUPTED. GENIE DOES NOT WARRANT THAT THE MATERIALS, DRAWINGS, SPECIFICATIONS OR THE SERVER THAT MAKES THEM AVAILABLE WILL NOT CONTAIN ANY COMPUTER VIRUSES THAT MAY INFECT THE USER'S COMPUTER EQUIPMENT, NETWORK OR RELATED SOFTWARE. GENIE DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE CORRECTNESS, ACCURACY OR RELIABILITY OF THE MATERIALS, DRAWINGS OR SPECIFICATIONS AND THE USER ASSUMES THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION, TO THE EXTENT PERMITTED BY LAW.</p>

<h2>LIMITATION OF LIABILITY</h2>
<p>IN NO EVENT SHALL GENIE BE LIABLE TO USER OR ANYONE ELSE FOR ANY INCIDENTAL, CONSEQUENTIAL, SPECIAL OR INDIRECT DAMAGES (INCLUDING, BUT NOT LIMITED TO, LOST PROFITS, TRADING LOSSES OR DAMAGES THAT RESULT FROM INCONVENIENCE, DELAY OR LOSS OF THE USE OF THE INFORMATION) ARISING OUT OF OR RELATED TO THE SITE, EVEN IF CAUSED BY THE NEGLIGENCE OF GENIE AND EVEN IF GENIE OR ANY PROVIDER OF THE INFORMATION HAS BEEN ADVISED OF OR IS OTHERWISE AWARE OF THE POSSIBILITY OF ERRORS THEREIN. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE MAY NOT APPLY IN PARTICULAR CASES OR JURISDICTIONS. IN NO EVENT SHALL GENIE'S TOTAL LIABILITY TO A USER FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION EXCEED THE AMOUNT PAID BY THE USER, IF ANY, FOR ACCESSING THIS SITE.</p>

<h2>INDEMNITY</h2>
<p>The User agrees to indemnify and hold Genie and its affiliates harmless from and against any and all claims, losses, liability, costs, and expenses (including, but not limited to, attorneys' fees) arising from the User's violation or breach of these Terms, arising from the User's violation of any third party's rights such as trademark, copyright, proprietary and privacy rights, or arising from User's violation of these terms of use or any applicable federal, state or local law, regulation or ordinance. This indemnification and hold harmless obligation will survive the termination of these Terms.</p>

<h2>GENERAL</h2>
<p>The User's access to and use of this Site and information available on or through this Site are subject to and shall be governed by and construed in accordance with all applicable federal laws of the United States and applicable laws of the State of Ohio and local governmental entities. Genie and User irrevocably consent to the exclusive jurisdiction of the courts located in Holmes County, Ohio and the federal courts situated in the State of Ohio in connection with any action arising under or in connection with these Terms or relating to the User's access of this Site, or any information available on or through this Site.</p>
<p>Use of this Site is unauthorized in any jurisdiction that does not give full effect to all provisions of this agreement, including without limitation this paragraph and the warranty disclaimers and liability exclusions above. Genie has endeavored to comply with all legal requirements known to it in creating and maintaining this Site, but makes no representation that materials on this Site are appropriate or available for use in any particular jurisdiction. Use of this Site is unauthorized in any jurisdiction where all or any portion of this Site may violate any legal requirements and you agree not to access this Site in any such jurisdiction. You are responsible for compliance with applicable laws. Any use in contravention of this provision or any provision of this agreement is at your own risk and, if any part of this agreement is invalid or unenforceable under applicable law, the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall govern such use.</p>
<p>You agree that Genie may at any time and without notice change the terms and conditions and notices under which this Site is offered. You agree that no joint venture, partnership, employment or agency relationship exists between you and Genie as a result of this agreement or your use of this Site.</p>
<p>Genieâ€™s performance of this agreement is subject to existing laws and legal process and nothing contained in this agreement is in derogation of Genieâ€™s right to comply with law enforcement requests or requirements relating to your use of this Site or information provided to or gathered by Genie with respect to such use.</p>
<p>This agreement constitutes the entire agreement between you and Genie with respect to this site. This agreement supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between you and Genie with respect to this Site. No modification of this agreement shall be effective unless it is authorized by Genie or its affiliates, or unless it is physically signed by a Genie officer. Any alleged waiver of any breach of this agreement shall not be deemed to be a waiver of any future breach. A printed version of this agreement and/or of any notice given by Genie in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement or your use of this Site to the same extent and subject to the same conditions as other business documents and records originally generated and maintained by Genie in printed form.</p>

<h2 id="privacy">PRIVACY POLICY</h2>
<p>The official Web site of Genie respects your privacy rights. Genieâ€™s Web site uses both session IDs and cookies to pass information from one page to another within their own domains. These technologies are used to record Web analytics to help us better understand our viewers and improve our Web sites. The information gathered includes the search engine or referring Web site that brought you to our company Web sites, what browser was used to view our sites, how many Web pages were viewed and the amount of time spent on each page. Our system does not record your name, e-mail address or any other personal information unless you provide it to us.</p>
<p class="last">Personally Identifiable Information is any information that would permit someone to contact or identify you including but not limited to your name, address, telephone/fax number, social security number, email address or any information you submit to Genie that identifies you individually.  Genieâ€™s website does not collect such information unless you provide us with information.  The following are examples of how you may submit information to us: in connection with an online or in-store purchase, through an online forum, your participation in a sweepstakes or contest.  Genie may use the Personally identifiable information through its website or through other means for such purposes as: verifying the identity of users; maintaining, administering and servicing usersâ€™ accounts or memberships; processing, servicing or enforcing transactions and sending related communications; providing services and support; providing product or service updates, promotional notices and offers, for use regarding sweepstakes or contests, providing other information about Genie and its affiliates, and responding to your questions, comments and instructions.</p>

</asp:Content>

